name: chatty_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  dio: ^5.8.0+1
  firebase_core: ^3.11.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.3

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  stacked_generator: ^1.6.1

flutter:
  uses-material-design: true
  # Svg Icons
  assets:
    - assets/App Logo/
    - assets/Arrows/
    - assets/Bottom Navigation/Chat/
    - assets/Bottom Navigation/AI Assistants/
    - assets/Bottom Navigation/History/
    - assets/Bottom Navigation/Account/
    - assets/Others/
    - assets/Images/User Image/
    - assets/Profile/
    - assets/Social/
    - assets/Auth Icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
